
export const product = [
    {
        id:1,
        offpercentage: '15% off',
        image: '/image/img-1 (1).jfif',
        promotion: false,
        top: false,
        category: 'boys',
        slug:'product1',
        title: 'Product One',
        price: 30.04,
        },
    {
        id:2,
        offpercentage: '12% off',
        image: '/image/img-1 (6).jfif',
        promotion: false,
        top: false,
        category: 'boys',
        slug:'product2',
        title: 'Product Two',
        price: 60.58,
         },
    {
        id:3,
        offpercentage: '10% off',
        image: '/image/img-1 (8).jfif',
        promotion: false,
        top: false,
        category: 'boys',
        slug:'product3',
        title: 'Product Three',
         price: 40.04,
        },
    {
        id:4,
        offpercentage: '5% off',
        image: '/image/img-1.jfif',
        promotion: false,
        top: false,
        category: 'girls',
        slug:'product4',
        title: 'Product Four',
        price: 95.04,
         },
    {
        id:5,
        offpercentage: '50% off',
        image: '/image/img-6.jfif',
        promotion: false,
        top: false,
        category: 'girls',
        slug:'product5',
        title: 'Product Five',
        price: 80.04,
         },
    {
        id:6,
        offpercentage: '50% off',
        image: '/image/img-7.jfif',
        promotion: true,
        top: true,
        category: 'girls',
        slug:'product6',
        title: 'Product Six',
        price: 80.04,
         },
    {
        id:6,
        offpercentage: '50% off',
        image: '/image/img-7.jfif',
        promotion: true,
        top: true,
        category: 'men',
        slug:'product6',
        title: 'Product Six',
        price: 80.04,
         },
    {
        id:7,
        offpercentage: '50% off',
        image: '/image/img-7.jfif',
        promotion: true,
        top: true,
        category: 'men',
        slug:'product7',
        title: 'Product Seven',
        price: 88.04,
         },
    {
        id:8,
        offpercentage: '50% off',
        image: '/image/img-7.jfif',
        promotion: true,
        top: true,
        category: 'men',
        slug:'product8',
        title: 'Product Eight',
        price: 90.04,
         },
    {
        id:9,
        offpercentage: '50% off',
        image: '/image/img-7.jfif',
        promotion: true,
        top: true,
        category: 'ladies',
        slug:'product9',
        title: 'Product Nine',
        price: 800.04,
         },
    {
        id:10,
        offpercentage: '50% off',
        image: '/image/img-7.jfif',
        promotion: true,
        top: true,
        category: 'ladies',
        slug:'product10',
        title: 'Product Ten',
        price: 400.04,
         },
    {
        id:11,
        offpercentage: '50% off',
        image: '/image/img-7.jfif',
        promotion: true,
        top: true,
        category: 'ladies',
        slug:'product11',
        title: 'Product Eleven',
        price: 120.04,
         },
    {
        id:12,
        offpercentage: '50% off',
        image: '/image/img-7.jfif',
        promotion: true,
        top: true,
        category: 'couples',
        slug:'product12',
        title: 'Product Twelve',
        price: 190.04,
         },
    {
        id:13,
        offpercentage: '50% off',
        image: '/image/img-7.jfif',
        promotion: true,
        top: true,
        category: 'couples',
        slug:'product13',
        title: 'Product Thirteen',
        price: 180.04,
         },
    {
        id:14,
        offpercentage: '50% off',
        image: '/image/img-7.jfif',
        promotion: true,
        top: true,
        category: 'couples',
        slug:'product14',
        title: 'Product Fourteen',
        price: 160.04,
         },
    {
        id:15,
        offpercentage: '50% off',
        image: '/image/img-7.jfif',
        category: 'boys',
        promotion: true,
        top: true,
        slug:'product15',
        title: 'Product Fifteen',
        price: 170.04,
         },

]